"""empty message

Revision ID: 45b2cee6794
Revises: 51e2c29ad95
Create Date: 2020-04-20 21:37:39.054844

"""

# revision identifiers, used by Alembic.
revision = '45b2cee6794'
down_revision = '51e2c29ad95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('first_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('first_name', 'last_name', name='user_pkey')
    )
    ### end Alembic commands ###
