"""empty message

Revision ID: 5050cf3151a
Revises: 45b2cee6794
Create Date: 2020-04-20 21:44:08.028027

"""

# revision identifiers, used by Alembic.
revision = '5050cf3151a'
down_revision = '45b2cee6794'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
